### ISSUE TITLE
请问后续内容还更新吗

### ISSUE THREAD

**Issue by jhmarryme** [zq99299/note-architect#1]
写的很好, 对我很有帮助,期待后续更新

**Comment by zq99299** [comment]
直通车这个，我还在学习，我也是工作业余时间学习，学习进度受加班等因素影响，不过我觉得这门课程还可以，我会坚持学完的

**Comment by jhmarryme** [comment]
好的 期待后续更新

**Comment by zq99299** [comment]
这个以后可以关注语雀，https://www.yuque.com/mrcode.cn/note-ztc

我发现笔记越来越多，想要找到笔记的时候很困难，以后新增的笔记应该都会使用语雀来记录了，还有全文搜索，较方便

**Comment by jhmarryme** [comment]
已关注
