### ISSUE TITLE
茶哥能不能提供一个支付的账号

### ISSUE THREAD

**Issue by NebulorDang** [zq99299/note-architect#7]
茶哥你好，能不能提供一个微信支付宝的支付账号，我做到这卡住了没账号

**Comment by zq99299** [comment]
> 茶哥你好，能不能提供一个微信支付宝的支付账号，我做到这卡住了没账号

不好意思，昨天手机上看到，想回复来着，发现没登录，就没操作了，
现在才想起来，我也没有个人的支付账户，所以你直接用那个课程提供的支付中心测试就行了。

**Comment by NebulorDang** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by NebulorDang** [comment]
好的已解决
